### ISSUE TITLE
Makefile:58: recipe for target 'bmdcapture' failed

### ISSUE THREAD

**Issue by Lawdie** [lu-zero/bmdtools#104]
Can't seem to get any of it to build correctly. I followed the instructions on the Wiki (Including insalling all the applications from source).

Ubuntu 18.04 LTS

Flattened and rebuilt the machine a few times trying get it working. This is the log.

/home/a/Downloads/bmdtools-master# make SDK_PATH=/home/a/Downloads/BMSDK/Linux/include/
g++ -o bmdcapture bmdcapture.cpp modes.cpp /home/a/Downloads/BMSDK/Linux/include//DeckLinkAPIDispatch.cpp pkg-config --cflags libavcodec libavformat libswscale libavutil -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -Wno-multichar -I /home/a/Downloads/BMSDK/Linux/include/ -fno-rtti -g pkg-config --libs libavcodec libavformat libswscale libavutil -lm -ldl -lpthread
bmdcapture.cpp: In function ‘void avpacket_queue_flush(AVPacketQueue*)’:
bmdcapture.cpp:95:33: warning: ‘void av_free_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
av_free_packet(&pkt->pkt);
^
In file included from /usr/local/include/libavformat/avformat.h:258:0,
from bmdcapture.cpp:37:
/usr/local/include/libavcodec/avcodec.h:3908:6: note: declared here
void av_free_packet(AVPacket pkt);
^~~~~~~~~~~~~~
bmdcapture.cpp: In function ‘int avpacket_queue_put(AVPacketQueue, AVPacket*)’:
bmdcapture.cpp:117:47: warning: ‘int av_dup_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
if (pkt != &flush_pkt && av_dup_packet(pkt) < 0) {
^
In file included from /usr/local/include/libavformat/avformat.h:258:0,
from bmdcapture.cpp:37:
/usr/local/include/libavcodec/avcodec.h:3899:5: note: declared here
int av_dup_packet(AVPacket pkt);
^~~~~~~~~~~~~
modes.cpp: In function ‘void print_display_mode(IDeckLinkDisplayMode, int)’:
modes.cpp:38:5: error: ‘BMDDisplayModeSupport’ was not declared in this scope
BMDDisplayModeSupport displayModeSupport;
^~~~~~~~~~~~~~~~~~~~~
modes.cpp:38:5: note: suggested alternative: ‘bmdDisplayModeSupports3D’
BMDDisplayModeSupport displayModeSupport;
^~~~~~~~~~~~~~~~~~~~~
bmdDisplayModeSupports3D
Makefile:58: recipe for target 'bmdcapture' failed
make: *** [bmdcapture] Error 1

**Comment by Lawdie** [comment]
Managed to resolve it, the build will fail if you use SDK 11.2. SDK 10.11.4 is the newest build that will work

**Comment by lu-zero** [comment]
I was traveling I guess the codebase needs to be updated.

**Comment by kubriel** [comment]
this affects me also
