### ISSUE TITLE
fails to build on gentoo

### ISSUE THREAD

**Issue by mundis** [lu-zero/bmdtools#44]
make SDK_PATH=/usr/include
g++ -o bmdcapture bmdcapture.cpp modes.cpp /usr/include/DeckLinkAPIDispatch.cpp `pkg-config --cflags libavcodec libavformat libswscale libavutil` -D__STDC_CONSTANT_MACROS -Wno-multichar -I /usr/include -fno-rtti -g `pkg-config --libs libavcodec libavformat libswscale libavutil` -lm -ldl -lpthread
bmdcapture.cpp: In function 'int main(int, char**)':
bmdcapture.cpp:730:64: error: 'av_dict_parse_string' was not declared in this scope
             if (av_dict_parse_string(&opts, optarg, "=", ":", 0) < 0) {
                                                                ^
Makefile:55: recipe for target 'bmdcapture' failed
make: *** [bmdcapture] Error 1

**Comment by lu-zero** [comment]
Unmask and install either libav-11 or libav-9999.

**Comment by lu-zero** [comment]
libav-11.3 should be even stable now.
