### ISSUE TITLE
make: *** [bmdcapture] Erreur 1

### ISSUE THREAD

**Issue by Frenchline** [lu-zero/bmdtools#46]
Hi,

i am trying to compile bmdtools but i got this error.

g++ -o bmdcapture bmdcapture.cpp modes.cpp ../Linux/include/DeckLinkAPIDispatch.cpp `pkg-config --cflags libavcodec libavformat libswscale libavutil` -D__STDC_CONSTANT_MACROS -Wno-multichar -I ../Linux/include -fno-rtti -g `pkg-config --libs libavcodec libavformat libswscale libavutil` -lm -ldl -lpthread
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
bmdcapture.cpp:34:34: erreur fatale: libavformat/avformat.h : Aucun fichier ou dossier de ce type
compilation terminée.
make: *** [bmdcapture] Erreur 1

libav is install. I am running Ubuntu 12.04

Any ideas? 

Thanks

**Comment by lu-zero** [comment]
Install libav from sources or the -devel package if it provides libav 11

**Comment by Frenchline** [comment]
Thanks lu-zero for you help

i installed libav 11 ans it seems to have worked

g++ -o bmdcapture bmdcapture.cpp modes.cpp ../Linux/include/DeckLinkAPIDispatch.cpp `pkg-config --cflags libavcodec libavformat libswscale libavutil` -D__STDC_CONSTANT_MACROS -Wno-multichar -I ../Linux/include -fno-rtti -g `pkg-config --libs libavcodec libavformat libswscale libavutil` -lm -ldl -lpthread
g++ -o bmdplay bmdplay.cpp modes.cpp ../Linux/include/DeckLinkAPIDispatch.cpp `pkg-config --cflags libavcodec libavformat libswscale libavutil` -D__STDC_CONSTANT_MACROS -Wno-multichar -I ../Linux/include -fno-rtti -g `pkg-config --libs libavcodec libavformat libswscale libavutil` -lm -ldl -lpthread
bmdplay.cpp: In member function ‘bool Player::Init(int, int, int)’:
bmdplay.cpp:476:39: attention : format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat]
bmdplay.cpp:529:15: attention : ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:3195) [-Wdeprecated-declarations]
bmdplay.cpp:529:35: attention : ‘AVFrame* avcodec_alloc_frame()’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:3195) [-Wdeprecated-declarations]
g++ -o bmdgenlock genlock.cpp ../Linux/include/DeckLinkAPIDispatch.cpp `pkg-config --cflags libavcodec libavformat libswscale libavutil` -D__STDC_CONSTANT_MACROS -Wno-multichar -I ../Linux/include -fno-rtti -g `pkg-config --libs libavcodec libavformat libswscale libavutil` -lm -ldl -lpthread

But when i tried this :
bmdcapture -h
bmdcapture : commande introuvable

what did i missed?

thanks a lot

**Comment by lu-zero** [comment]
copy it on /usr/bin

**Comment by Frenchline** [comment]
Thanks for your time, it works now. :-)
