### ISSUE TITLE
Audio sample_fmt not supported?

### ISSUE THREAD

**Issue by stevenbell** [lu-zero/bmdtools#49]
I've built bmdcapture, but when I try to run it, I get the error

    [pcm_s16le @ 0x1b9aca0] Specified sample_fmt is not supported.
    could not open codec

I've built my own libav, so that might be the problem.  However, pcm_s16le is supported, from everything I can tell:

    > ../libav/avconv -codecs | grep -i pcm
    avconv version v11.2, Copyright (c) 2000-2014 the Libav developers
      built on Mar  4 2015 15:03:14 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
    ...
    DEA..S pcm_s16le            PCM signed 16-bit little-endian
    DEA..S pcm_s16be            PCM signed 16-bit big-endian
    ...

    >../libav/avconv -sample_fmts
    name   depth
    u8        8 
    s16      16 
    s32      32 
    ....

Ubuntu 14.04, libav 11.2 with libavutil 54.3.0.  Latest bmdtools from git.

**Comment by lu-zero** [comment]
```
ldd bmdcapture
```
Shows it linking to the right libraries? Could you please also paste the command line in use?

**Comment by stevenbell** [comment]
Thanks for the quick reply.  It was in fact linking to the wrong libraries, and it's working after a rebuild.
