### ISSUE TITLE
Capture video with bmdtools using DekckLink 4K Extreme Capture Card

### ISSUE THREAD

**Issue by tomaszed** [lu-zero/bmdtools#50]
Hello,

Can anyone help me to capture video using bmdtools with DekcLink 4K Extreme with ffpmeg.
I have a trouble tocapture frames from my Set-Top-Box that he have color space output Y'CbCr 4:4:4 and capturing from this color space is a card feature.

Thanks
Tomas

**Comment by lu-zero** [comment]
FFmpeg is not supported.

**Comment by tomaszed** [comment]
Can you help me to capture frame using bmdtools with DeckLink 4K Extreme ?

**Comment by lu-zero** [comment]
which driver are you using btw? I cannot find that pixel format.

**Comment by tomaszed** [comment]
I'm using the Desktop Video 10.3.7 from Black Magic and i guess it's the last version for.
I'm in UNIX envirment and i can't found wich solution to get and capture video from DeckLink 4K extreme.
