### ISSUE TITLE
Possible pixel format issue - yuv8

### ISSUE THREAD

**Issue by kelfish** [lu-zero/bmdtools#51]
__Overview__ 
When used with pixel format (`-p`) `yuv8` or not supplied `avconv` sees the incoming raw video as `rgb555le`. This is causing me color issues when generating videos or images from our feed. 

I have managed to get around this by using `yuv10` - `avconv` then sees the stream as `yuv422p10le`.

I am using the latest bmdtools from the repository with the latest firmware, SDK and drivers from Blackmagic. On Ubuntu 14.04.

__Hardware used__

    0:	/dev/blackmagic/io0 [DeckLink Mini Recorder]	0x45	OK

__Command used__

    /usr/bin/bmdcapture -C 0 -m 11 -V 4 -p yuv8 -f pipe:1 -n 1 -F nut -o strict=experimental:syncpoints=none | /usr/local/bin/avconv -vsync passthrough -y -i - -f image2 - > test.jpg

__avconv Output__

When using `yuv8`:

    Input #0, nut, from 'pipe:':
      Metadata:
        encoder         : Lavf55.12.0
      Duration: N/A, start: 0.000000, bitrate: N/A
        Stream #0.0: Video: rawvideo, rgb555le, 1280x720, 59.94 tbn
        Stream #0.1: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s

When using `yuv10`:

    Input #0, nut, from 'pipe:':
      Metadata:
        encoder         : Lavf55.12.0
      Duration: N/A, start: 0.000000, bitrate: N/A
        Stream #0.0: Video: v210, yuv422p10le, 1280x720, 59.94 tbn
        Stream #0.1: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s

**Comment by lu-zero** [comment]
Fixed, I forgot nut relies on codec_tag for raw formats... I'll address that in Libav as well since it is quite annoying.

**Comment by kelfish** [comment]
Thanks for such a quick response and fix! That did it... `avconv` sees it correctly now:

    Stream #0.0: Video: rawvideo, uyvy422, 1280x720, 59.94 tbn
