### ISSUE TITLE
in case of novideo, color bars does not work with 10 bit

### ISSUE THREAD

**Issue by dericed** [lu-zero/bmdtools#54]
With no video source on 8 bit color bars are shown, but the data is only in uyvy422 (see https://github.com/lu-zero/bmdtools/blob/master/bmdcapture.cpp#L407-L408). I propose adding a version for v210.
```
bmdcapture -m 0 -V 4 -A 2 -c 8 -s 32 -p 10 -F nut -f pipe:1 | avplay -
```
![colorbars10](https://cloud.githubusercontent.com/assets/762604/8022375/41ffe216-0c9b-11e5-89e3-c6342dbf345d.jpg)

**Comment by lu-zero** [comment]
Yes, makes sense.

**Comment by dericed** [comment]
Closing this request in favor of https://github.com/lu-zero/bmdtools/issues/55.
