### ISSUE TITLE
ffmpeg.exe memory leak ? Help please

### ISSUE THREAD

**Issue by Csharper1972** [lu-zero/bmdtools#60]
I'm using ffmpeg to compress batch of images in real time and create a video mp4 file all in real time.
The problem is i have 1200 images and after 3-5 seconds the ffmpeg.exe usage memory raise from 0.1MB to over 1GB also the hard disk from 0MB/s jump to over 53MB/s

This make my whole pc slow stuck freeze.

I posted my csharp code using the ffmpeg here: http://ffmpeg.gusari.org/viewtopic.php?f=11&t=2204&sid=254ad03ccf99c6065039136ef95c4267

And here : http://stackoverflow.com/questions/31149752/why-when-using-ffmpeg-to-create-video-file-in-real-time-the-ffmpeg-exe-take-over

Maybe someone can look at and see a problem ? I can't find any problem with my code.
Is that known problem the memory leak ?

**Comment by lu-zero** [comment]
The problem does not seem related to bmdtools, you can try with `avconv` please?
I do not use ffmpeg and I cannot fix it for you anyway.
