### ISSUE TITLE
DeckLink 4K Extreme 12G with Quad SDI

### ISSUE THREAD

**Issue by ggnull35** [lu-zero/bmdtools#63]
Hello,

I have DeckLink 4K Extreme 12G with Quad SDI. I tried to connect 4 x 3G connection with shown diagram (12G In A, 12G In B, 6G In C, 6G In D).

![pci](https://cloud.githubusercontent.com/assets/8988826/8925000/a6f14158-350c-11e5-9b0b-6728d14beef5.png)

I tried bmdcapture to capture raw video using mode 21.

bmdcapture: invalid option -- 'd'
Usage: bmdcapture -m <mode id> [OPTIONS]

    -m <mode id>:
-> DeckLink 4K Extreme 12G (-C 0 )

Supported video input display modes and pixel formats:
         0:   NTSC                       720 x 486         29.97 FPS
         1:   PAL                        720 x 576            25 FPS
         2:   1080p23.98                 1920 x 1080      23.976 FPS
         3:   1080p24                    1920 x 1080          24 FPS
         4:   1080p25                    1920 x 1080          25 FPS
         5:   1080p29.97                 1920 x 1080       29.97 FPS
         6:   1080p30                    1920 x 1080          30 FPS
         7:   1080i50                    1920 x 1080          25 FPS
         8:   1080i59.94                 1920 x 1080       29.97 FPS
         9:   1080i60                    1920 x 1080          30 FPS
        10:   1080p50                    1920 x 1080          50 FPS
        11:   1080p59.94                 1920 x 1080     59.9401 FPS
        12:   1080p60                    1920 x 1080          60 FPS
        13:   720p50                     1280 x 720           50 FPS
        14:   720p59.94                  1280 x 720      59.9401 FPS
        15:   720p60                     1280 x 720           60 FPS
        16:   1080p23.98 DCI 2K          2048 x 1080      23.976 FPS
        17:   1080p24 DCI 2K             2048 x 1080          24 FPS
        18:   1080p25 DCI 2K             2048 x 1080          25 FPS
        19:   2160p23.98                 3840 x 2160      23.976 FPS
        20:   2160p24                    3840 x 2160          24 FPS
        21:   2160p25                    3840 x 2160          25 FPS
        22:   2160p29.97                 3840 x 2160       29.97 FPS
        23:   2160p30                    3840 x 2160          30 FPS
        24:   2160p50                    3840 x 2160          50 FPS
        25:   2160p59.94                 3840 x 2160     59.9401 FPS
        26:   2160p60                    3840 x 2160          60 FPS
        27:   2160p23.98 DCI 4K          4096 x 2160      23.976 FPS
        28:   2160p24 DCI 4K             4096 x 2160          24 FPS
        29:   2160p25 DCI 4K             4096 x 2160          25 FPS

But I get no frames detected massage.

I digged in and found also Capture tool in Linux SDK can not capture 4K video. The Capture tool only detects 1080p@25fps on 12G SDI In A. So, it is not an issue of bmdcapture actually.

Is there any module or command line parameter to enable all inputs ? Do I do something missing ?

Kind Regards,

**Comment by haakonnessjoen** [comment]
As far as I know, you have to usa a blackmagic multiplexer to make your
4x3G to 12G and use input A with a single cable.

Håkon

Den tirsdag 28. juli 2015 skrev ggnull35 <notifications@github.com>
følgende:

> Hello,
>
> I have DeckLink 4K Extreme 12G with Quad SDI. I tried to connect 4 x 3G
> connection with shown diagram (12G In A, 12G In B, 6G In C, 6G In D).
>
> [image: pci]
> <https://cloud.githubusercontent.com/assets/8988826/8925000/a6f14158-350c-11e5-9b0b-6728d14beef5.png>
>
> I tried bmdcapture to capture raw video using mode 21.
>
> bmdcapture: invalid option -- 'd'
> Usage: bmdcapture -m [OPTIONS]
>
> -m <mode id>:
>
> -> DeckLink 4K Extreme 12G (-C 0 )
>
> Supported video input display modes and pixel formats:
> 0: NTSC 720 x 486 29.97 FPS
> 1: PAL 720 x 576 25 FPS
> 2: 1080p23.98 1920 x 1080 23.976 FPS
> 3: 1080p24 1920 x 1080 24 FPS
> 4: 1080p25 1920 x 1080 25 FPS
> 5: 1080p29.97 1920 x 1080 29.97 FPS
> 6: 1080p30 1920 x 1080 30 FPS
> 7: 1080i50 1920 x 1080 25 FPS
> 8: 1080i59.94 1920 x 1080 29.97 FPS
> 9: 1080i60 1920 x 1080 30 FPS
> 10: 1080p50 1920 x 1080 50 FPS
> 11: 1080p59.94 1920 x 1080 59.9401 FPS
> 12: 1080p60 1920 x 1080 60 FPS
> 13: 720p50 1280 x 720 50 FPS
> 14: 720p59.94 1280 x 720 59.9401 FPS
> 15: 720p60 1280 x 720 60 FPS
> 16: 1080p23.98 DCI 2K 2048 x 1080 23.976 FPS
> 17: 1080p24 DCI 2K 2048 x 1080 24 FPS
> 18: 1080p25 DCI 2K 2048 x 1080 25 FPS
> 19: 2160p23.98 3840 x 2160 23.976 FPS
> 20: 2160p24 3840 x 2160 24 FPS
> 21: 2160p25 3840 x 2160 25 FPS
> 22: 2160p29.97 3840 x 2160 29.97 FPS
> 23: 2160p30 3840 x 2160 30 FPS
> 24: 2160p50 3840 x 2160 50 FPS
> 25: 2160p59.94 3840 x 2160 59.9401 FPS
> 26: 2160p60 3840 x 2160 60 FPS
> 27: 2160p23.98 DCI 4K 4096 x 2160 23.976 FPS
> 28: 2160p24 DCI 4K 4096 x 2160 24 FPS
> 29: 2160p25 DCI 4K 4096 x 2160 25 FPS
>
> But I get no frames detected massage.
>
> I digged in and found also Capture tool in Linux SDK can not capture 4K
> video. The Capture tool only detects 1080p@25fps on 12G SDI In A. So, it
> is not an issue of bmdcapture actually.
>
> Is there any module or command line parameter to enable all inputs ? Do I
> do something missing ?
>
> Kind Regards,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lu-zero/bmdtools/issues/63>.
>


-- 
Håkon

**Comment by ggnull35** [comment]
Yep, it was like that but, they released this addon card for direct connection.

This is the news link:
https://www.blackmagicdesign.com/press/release/20150610-01

**Comment by lu-zero** [comment]
If you can give me access to a system probably I can try to see why it isn't working out of box.

**Comment by ggnull35** [comment]
Thank you lu-zero, tomorrow morning I will PM you root access for SSH to server.
I will place SDK and latest driver in root directory.

**Comment by ggnull35** [comment]
Hello Luca,

I sent email to you for connection details. Thank you for your support.

Kind Regards,

**Comment by ggnull35** [comment]
I got explanation from BMD Developer team:

DeckLink 4K Extreme 12G currently does not support Quad 3G Level B capture. This support is planned however no timeline for release currently exists.

**Comment by lu-zero** [comment]
Makes sense I guess..
