### ISSUE TITLE
Mac compilation problems

### ISSUE THREAD

**Issue by nbd712** [lu-zero/bmdtools#66]
I've been having a rough time trying to compile this on OSX 10.9. I've got all the libraries correctly placed, however once make is run I run into this error:  Undefined symbols for architecture x86_64: then a long list of items.

Any ideas as to what could be the problem?

**Comment by nbd712** [comment]
Totally my bad, turns out I needed to run:

"make PKG_CONFIG_PATH=/usr/local/lib/pkgconfig" to define the PKG_CONFIG_PATH variable.

**Comment by lu-zero** [comment]
Ah, looks like my answer remained in the email client.

For reference:
- please provide the console output
- make sure you are not using the wrong `pkg-config`
- make sure you do not have multiple libraries installed in different paths, the one you want to use might have a lower priority.

Glad it had been found, you can also use [this tap](https://github.com/luminem/homebrew-bmdtools) in case.
