### ISSUE TITLE
Delay 2s with bmdplay

### ISSUE THREAD

**Issue by khachung** [lu-zero/bmdtools#67]
Hi,

I have Blackmagic Intensity Pro 4K on a server run Debian Jessie. I tried to capture and play on TV with bmdcapture and bmdplay.
I used this command:
./bmdcapture -C 0 -m 7 -n 1500 -F nut -f pipe:1 | ./bmdplay -C 0 -m 7 -f pipe:0
Video shown on TV but was delayed 2s. How can I play real-time video?

Thanks,

**Comment by lu-zero** [comment]
```
            -b <num>             Milliseconds of pre-buffering before playback (default = 2000 ms)
```

You need to tune this option.

I hope it helps =)

**Comment by khachung** [comment]
It works fine. Awesome. Thank you very much!
Now I also want to store recorded video with this command: 
./bmdcapture -C 0 -m 7 -n 1500 -F nut -f pipe:1  | tee > test.avi | ./bmdplay -C 0 -m 7 -f pipe:0
Because I want to add trademark to video so I changed your bmdcapture. However, video shown on TV have no trademark as stored video.

**Comment by lu-zero** [comment]
You can use [avconv](https://www.libav.org/avconv.html#overlay-1) to add it.

**Comment by khachung** [comment]
Hi Luca,

Thanks for the reply. But what I want is to get the data from the
bmdcapture for 2 pipe line: recording and streaming. I used a tee, but
failed. Can you show me how to handle it or let me know if I use the wrong
tee command.
Thank you very much.

2015-11-30 1:59 GMT+07:00 Luca Barbato <notifications@github.com>:
