### ISSUE TITLE
bmdplay 3840x2160 HDMI out problem

### ISSUE THREAD

**Issue by ggnull35** [lu-zero/bmdtools#68]
Hello,

I have Blackmagic Decklink 12G Extreme Card. I can push out HDMI video with 1080p resolution without any problem. However, same video with UHD resolution makes problem. Such like upper 2K frames and lower 2K frames do not place on right areas.

1080p test:
avconv  -re -i test.mp4 -c:v rawvideo -c:a pcm_s16le -ac 2 -f nut -s 1920x1080 - | bmdplay -f pipe:0 -m 10 -C 0 -O 3

![image](https://cloud.githubusercontent.com/assets/8988826/11435464/8a9a10d4-94e3-11e5-8dde-2b52e47397c2.png)

![image](https://cloud.githubusercontent.com/assets/8988826/11435473/a864eac6-94e3-11e5-939b-176d21f8ec31.png)

2160p test:
avconv  -re -i test.mp4 -c:v rawvideo -c:a pcm_s16le -ac 2 -f nut -s 3840x2160 - | bmdplay -f pipe:0 -m 24 -C 0 -O 3

![image](https://cloud.githubusercontent.com/assets/8988826/11435485/bc942796-94e3-11e5-90f7-b97626f0fd80.png)

![image](https://cloud.githubusercontent.com/assets/8988826/11435500/f1547044-94e3-11e5-99e5-29b3f9ca81cb.png)

Test video was HEVC & AAC encodded in YUV 4:2:0 at 50 fps. I tested different framerates on 3840x2160 always same problem.

**Comment by lu-zero** [comment]
Can you please provide me the sample file? `bmdplay` is really simple: it copies what is gets in. Are you 100% sure the video mode is the correct one for that content?

**Comment by ggnull35** [comment]
Yes, video mode 24 means 3840x2160 at 50 fps. So the video is same. Please download and see the test file.

- Please download sample file from:
http://we.tl/lB0h1rGbIG

**Comment by lu-zero** [comment]
Can you please try the TestPattern program?

**Comment by ggnull35** [comment]
Yes i tested it. TestPattern works fine at 3840x2160@50.

**Comment by lu-zero** [comment]
I know that might be stupid but... maybe you forgot to pass `-pix_fmt uyvy422` ?

**Comment by ggnull35** [comment]
I tried adding -pix_fmt uyvy422 and result is same. Output video broken again as given images on 1st post.

**Comment by lu-zero** [comment]
After spending a good deal of the day on it I guess we can point our finger to the hardware.

Let see if bmd can help you about it.
