### ISSUE TITLE
-d parameters give Segmentation Fault

### ISSUE THREAD

**Issue by ggnull35** [lu-zero/bmdtools#69]
Hi,

When passed -d 0 or -d 1 to bmdcapture, app gives Segmentation Fault.

If I modify Line 782 from "draw_bars = atoi(optarg)" to "draw_bars = 0" or "draw_bars = 1", it works.

Best wishes.

**Comment by lu-zero** [comment]
There is a `:` missing, fixed.

**Comment by ggnull35** [comment]
Thank you Luca :+1:  You are the best !

**Comment by doogaille** [comment]
Work like a charm ;-) I think you can close issue

**Comment by lu-zero** [comment]
Closing then =)
