### ISSUE TITLE
[nut @ 0x41ca6a0] Error stream_count is (32767)

### ISSUE THREAD

**Issue by aslobodyanuyk** [lu-zero/bmdtools#70]
I'm try to use "-o strict=experimental:syncpoints=none" for solving the memory leak issue. But had ffmpeg error:

`bmdcapture -C 3 -m 2 -A 2 -V 4 -F nut -o strict=experimental:syncpoints=none -f pipe:1 | ffmpeg -re -i - -y -b:v 1500k -acodec mp3 -ar 22050 -vcodec libx264 -f flv "rtmp://server/stream"`

> ffmpeg version N-77342-gc67cf84d Copyright (c) 2000-2015 the FFmpeg developers
>   built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
>   configuration: --prefix=/home/admin/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/admin/ffmpeg_build/include --extra-ldflags=-L/home/admin/ffmpeg_build/lib --bindir=/home/admin/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
>   libavutil      55. 11.100 / 55. 11.100
>   libavcodec     57. 18.100 / 57. 18.100
>   libavformat    57. 20.100 / 57. 20.100
>   libavdevice    57.  0.100 / 57.  0.100
>   libavfilter     6. 21.100 /  6. 21.100
>   libswscale      4.  0.100 /  4.  0.100
>   libswresample   2.  0.101 /  2.  0.101
>   libpostproc    54.  0.100 / 54.  0.100
> [nut @ 0x41ca6a0] Error stream_count is (32767)

How to solve this? Maybe I do something wrong?

**Comment by lu-zero** [comment]
You are using FFmpeg, looks like the nut support there is somehow broken, please use Libav and report back, in case it is still not working.
