### ISSUE TITLE
ffmpeg and current compatibility state

### ISSUE THREAD

**Issue by cowai** [lu-zero/bmdtools#72]
Hi,

I am using bmdtools and specifically bmdcapture along with https://github.com/lu-zero/libav.
There is some very nice filters only available in ffmpeg now (like bwdif and mcdeint) and I was wondering if the changes made to https://github.com/lu-zero/libav is necessary today.

As a workaround, could I pipe from libav to ffmpeg with nut as the container without issues you think?

I could just test this, but I am without any available hardware at the moment so I was hoping if @lu-zero had answers to this.

**Comment by lu-zero** [comment]
You can port the filters you like to Libav, it would help more people and would be quite a large thank you for my efforts. =)

**Comment by cowai** [comment]
@lu-zero 
Thank you so much for this project. It has helped a non profit that I work for immensely.
As I am no C developer maybe we could hire you to help with this?

**Comment by lu-zero** [comment]
Would be great =)

**Comment by me-vlad** [comment]
@cowai JFYI - bmdcapture works with ffmpeg, but not supported by @lu-zero
For example bmdtools from http://repo.enetres.net/ (centos 6 repo) - works fine with recent ffmpeg (I use static ffmpeg builds from http://johnvansickle.com/ffmpeg/).
So you can test  bmdcapture/ffmpeg combination on your workflow, but @lu-zero dont likes ffmpeg related bugs ;)

**Comment by lu-zero** [comment]
Surely I'm not happy to have people asking for free support for using my code with a project I do not belong to.
