### ISSUE TITLE
Compile unter Windows (msys2)

### ISSUE THREAD

**Issue by jb-alvarado** [lu-zero/bmdtools#73]
Hello,
I was trying to compile your tool under Windows. Msys2 has a working widl - we use it for our ffmpeg build script: [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite/tree/master/build/extras)

But I don't get it. The make file I don't get to work, so I try it manually like this:

 `g++ -o bmdcapture.exe bmdcapture.cpp modes.cpp -ID:/_System/msys2-64-Ma16/local32/include -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS $CXXFLAGS -Wno-multichar -I../extras -fno-rtti -g $LDFLAGS -LD:/_System/msys2-64-Ma16/local64/lib -lavformat -lws2_32 -lSecur32 -lmingw32 -lSDLmain -lSDL -lmingw32 -lSDLmain -lSDL -liconv -lm -luser32 -lgdi32 -lwinmm -ldxguid -mconsole -lm -llzma -lbz2 -lz -lpsapi -ladvapi32 -lshell32 -lavcodec -lws2_32 -lSecur32 -lmingw32 -lSDLmain -lSDL -lmingw32 -lSDLmain -lSDL -liconv -lm -luser32 -lgdi32 -lwinmm -ldxguid -mconsole -lm -llzma -lbz2 -lz -lpsapi -ladvapi32 -lshell32 -lswresample -lm -lswscale -lm -lavutil -lm -ldl -lpthread
`
But this is the result:
[gist](https://gist.github.com/jb-alvarado/a4ef1817d60ba2d39371)

Any Idea, what I can do?

Regards!
Jonathan

**Comment by lu-zero** [comment]
FFmpeg is not supported.
