### ISSUE TITLE
bmdcapture tainted, ubuntu kernel in Oops state (sometimes)

### ISSUE THREAD

**Issue by advera68** [lu-zero/bmdtools#76]
Dear Friend, 

First of all, thank you very much for developing so valuable tool. I have been using bmdcapture and bmdplay for a long time with different BlackMagic Decklink model cards, like MIni Recorder, Mini Monitor and Duo.  

These tools  work pretty well, I use them  in combination with ffmpeg and vlc, always under Ubuntu  14.04.1 LTS  and  '16.04.1 LTS', both 64 bits version, but sometimes kernel enters in an Oops state with a message indicating 'bmdcapture' process is responsible for that situation. I enclose a copy of a typical message shown in syslog below.

I guess  the more I stop 'bmdcapture' process, the more likely is that kernel enter in Oops state. For example, suppose I am recording a typical SDI signal from a TV channel and I stop bmdcatpure when a program, ad spot or anyother event occurs, i.e. it can happen hundred times a day. Well, in these conditions kernel is likely to enter in Oops state once a week, more or less.

I work always with  PAL  720 x 576  25 FPS and  HD 1080i 50  1920 x 1080   25 FPS and I  use 'kill -9' command in order to stop bmdcapture.

If you want more information, please don't hesitate to contact me.

Best Regards.

----------------------------------------------------

P.S.  Example of message in syslog file:

Aug 11 23:49:47 chopper1 kernel: [47573.592592] BUG: unable to handle kernel NULL pointer dereference at 00000000000000dc
Aug 11 23:49:47 chopper1 kernel: [47573.683373] IP: [<ffffffffc04fa43e>] dl_unmap_user_pages+0x2e/0x60 [[**blackmagic]**
Aug 11 23:49:47 chopper1 kernel: [47573.774688] PGD 0
Aug 11 23:49:47 chopper1 kernel: [47573.864902] **Oops**: 0002 [#1] SMP
Aug 11 23:49:47 chopper1 kernel: [47573.954978] Modules linked in: arc4 md4 nls_utf8 cifs fscache intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp ipmi_ssif ipmi_devintf kvm_intel kvm dcdbas blackmagic(POE) irqbypass mei_me sb_edac mei edac_core input_leds ipmi_si lpc_ich 8250_fintek shpchp acpi_power_meter ipmi_msghandler mac_hid ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi autofs4 btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear crct10dif_pclmul crc32_pclmul hid_generic aesni_intel tg3 aes_x86_64 lrw usbhid gf128mul ptp glue_helper ahci ablk_helper megaraid_sas libahci cryptd hid pps_core wmi fjes
Aug 11 23:49:47 chopper1 kernel: [47574.472255] CPU: 1 PID: 147059 Comm**: bmdcapture**eTainted: P           OE   4.4.0-34-generic #53-Ubuntu

Aug 11 23:49:47 chopper1 kernel: [47574.581468] Hardware name: Dell Inc. PowerEdge R530/0HFG24, BIOS 1.6.2 01/08/2016
Aug 11 23:49:47 chopper1 kernel: [47574.691174] task: ffff880467eae040 ti: ffff880460cdc000 task.ti: ffff880460cdc000
Aug 11 23:49:47 chopper1 kernel: [47574.801325] RIP: 0010:[<ffffffffc04fa43e>]  [<ffffffffc04fa43e>] dl_unmap_user_pages+0x2e/0x60 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47574.913487] RSP: 0018:ffff880460cdfb00  EFLAGS: 00010202
Aug 11 23:49:47 chopper1 kernel: [47575.025228] RAX: ffff88010cf2c801 RBX: 0000000000000001 RCX: 00000000002f18cc
Aug 11 23:49:47 chopper1 kernel: [47575.137844] RDX: 0000000000000001 RSI: 00000000000000dc RDI: 00000000000000dc
Aug 11 23:49:47 chopper1 kernel: [47575.249910] RBP: ffff880460cdfb20 R08: 000000000001a060 R09: ffffffffc04facc3
Aug 11 23:49:47 chopper1 kernel: [47575.361794] R10: ffffea000433ca00 R11: ffffffffc04a9d60 R12: ffff88046121c800
Aug 11 23:49:47 chopper1 kernel: [47575.473569] R13: 00000000000000dc R14: 0000000000000001 R15: 0000000000000000
Aug 11 23:49:47 chopper1 kernel: [47575.585308] FS:  0000000000000000(0000) GS:ffff88046d240000(0000) knlGS:0000000000000000
Aug 11 23:49:47 chopper1 kernel: [47575.697617] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Aug 11 23:49:47 chopper1 kernel: [47575.809332] CR2: 00000000000000dc CR3: 0000000001e0a000 CR4: 00000000001406e0
Aug 11 23:49:47 chopper1 kernel: [47575.921597] Stack:
Aug 11 23:49:47 chopper1 kernel: [47576.032665]  ffff880464bda900 0000000000000000 0000000000000000 ffff8804567b1000
Aug 11 23:49:47 chopper1 kernel: [47576.146117]  ffff88045603d200 ffffffffc04a9e3a ffffc90002232870 ffffffffc04ea0d2
Aug 11 23:49:47 chopper1 kernel: [47576.259498]  ffffc90002232870 ffffffffc04ea26b ffffc90002268fc0 ffff8804567b1000
Aug 11 23:49:47 chopper1 kernel: [47576.372472] Call Trace:
Aug 11 23:49:47 chopper1 kernel: [47576.484293]  [<ffffffffc04a9e3a>] _ZN18IOMemoryDescriptor8completeEv+0x4a/0x70 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47576.598859]  [<ffffffffc04ea0d2>] ? _ZN26DaisyCutterDMASupportClass27releaseDMATransactionMemoryEP14DMAQueueEltRec+0x12/0xb0 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47576.716310]  [<ffffffffc04ea26b>] ? _ZN26DaisyCutterDMASupportClass26disposeDMATransactionGatedEP14DMAQueueEltRec+0xfb/0x170 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47576.833649]  [<ffffffffc04e1410>] ? _ZN22VideoInputSupportClass35stopMulticameraAutoTransitionActionEP8OSObjectmmmm+0x70/0x70 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47576.952463]  [<ffffffffc04e0a0c>] ? _ZN22VideoInputSupportClass18videoInputOffGatedEv+0x4c/0x360 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47577.071413]  [<ffffffffc04aae49>] ? _ZN26BlackmagicCommandGateClass9runActionEPFiP8OSObjectmmmmEmmmm+0x59/0x90 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47577.191823]  [<ffffffffc04e0eb2>] ? _ZN22VideoInputSupportClass21videoInputOffNotGatedEv+0x22/0xe0 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47577.312957]  [<ffffffffc04f3fac>] ? _ZN15UserClientClass13videoInputOffEv+0x2c/0x50 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47577.434519]  [<ffffffffc04f4acb>] ? _ZN15UserClientClass11clientCloseEv+0x13b/0x1a0 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47577.555746]  [<ffffffffc04a833d>] ? dl_release_user_client+0xd/0x30 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47577.677592]  [<ffffffffc04f90f9>] ? blackmagic_release+0x39/0x50 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47577.799917]  [<ffffffff8120efb4>] ? __fput+0xe4/0x220
Aug 11 23:49:47 chopper1 kernel: [47577.920554]  [<ffffffff8120f12e>] ? ____fput+0xe/0x10
Aug 11 23:49:47 chopper1 kernel: [47578.040260]  [<ffffffff8109ec1f>] ? task_work_run+0x7f/0xa0
Aug 11 23:49:47 chopper1 kernel: [47578.159686]  [<ffffffff81083d47>] ? do_exit+0x2e7/0xaf0
Aug 11 23:49:47 chopper1 kernel: [47578.278486]  [<ffffffff810845d3>] ? do_group_exit+0x43/0xb0
Aug 11 23:49:47 chopper1 kernel: [47578.396706]  [<ffffffff810907a2>] ? get_signal+0x292/0x600
Aug 11 23:49:47 chopper1 kernel: [47578.514355]  [<ffffffff8102e537>] ? do_signal+0x37/0x6f0
Aug 11 23:49:47 chopper1 kernel: [47578.631463]  [<ffffffffc04f91c9>] ? blackmagic_ioctl+0x49/0x60 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47578.749108]  [<ffffffff81220c3f>] ? do_vfs_ioctl+0x29f/0x490
Aug 11 23:49:47 chopper1 kernel: [47578.866349]  [<ffffffff8100320c>] ? exit_to_usermode_loop+0x8c/0xd0
Aug 11 23:49:47 chopper1 kernel: [47578.983582]  [<ffffffff81003c6e>] ? syscall_return_slowpath+0x4e/0x60
Aug 11 23:49:47 chopper1 kernel: [47579.100626]  [<ffffffff8182e050>] ? int_ret_from_sys_call+0x25/0x8f
Aug 11 23:49:47 chopper1 kernel: [47579.217379] Code: 00 00 55 48 89 e5 41 56 41 55 41 54 53 31 db 48 85 f6 49 89 fc 49 89 f5 41 89 d6 74 20 49 8b 3c dc 48 85 ff 74 0e 45 85 f6 74 04 <f0> 80 0f 10 e8 49 37 ca c0 48 83 c3 01 49 39 dd 75 e0 4c 89 e7
Aug 11 23:49:47 chopper1 kernel: [47579.460372] RIP  [<ffffffffc04fa43e>] dl_unmap_user_pages+0x2e/0x60 [blackmagic]
Aug 11 23:49:47 chopper1 kernel: [47579.582160]  RSP <ffff880460cdfb00>
Aug 11 23:49:47 chopper1 kernel: [47579.703200] CR2: 00000000000000dc
Aug 11 23:49:47 chopper1 kernel: [47580.103059] ---[ end trace 0fc26db8b17bd42e ]---
Aug 11 23:49:47 chopper1 kernel: [47580.224479] Fixing recursive fault but reboot is needed!

**Comment by lu-zero** [comment]
The kernel driver is out of my control =) You should report the issue to BMD directly.
