### ISSUE TITLE
bmdcapture doesn't register any signal handler 

### ISSUE THREAD

**Issue by advera68** [lu-zero/bmdtools#77]
Dear Friend, 

We have realized that  'bmdcapture' process does not register any signal handler, for example, suposse bmdcapture process has PID = 15372

cat /proc/15372/status

....
SigCgt: 0000000180000000
......

What in binary means 110000000000000000000000000000000 , i.e, no handler ofr any signal.

Do you think this issue could be the reason of what I told you some weeks ago ?

https://github.com/lu-zero/bmdtools/issues/76#issuecomment-239407932

I have modified my scripts using "/home/tv/Blackmagic_DeckLink_SDK_10.6.5/Linux/Samples/bin/x86_64/Capture" instead "bmdcapture", only to test, and I have realized no "oops kernel state" occurs using Capture instead "bmdcapture"

As we have realized  Capture process does have handler for several signals, we have thought this could be the reason for the different behaviour.

What do you think?

Regards.

**Comment by lu-zero** [comment]
Strange, `set_signal()` should be called so at least those signals should be registered..

**Comment by advera68** [comment]
Interessting ....  could you check it in one Ubuntu server ?

I have  three servers with the same behavior, all of them are Ubuntu, Ubuntu 16.04 LTS or  Ubuntu 14.04.1 LTS.

As a matter on fact, this issue hasn't been discovered by me, but by <developer@blackmagicdesign.com> . When I reported this issue with the sporadic kernel Oops they suggested to me trying with "Capture" and they were who really realized about the difference between signal handlers.

If you have something new, please, let me know.

Best regards.

**Comment by lu-zero** [comment]
If you comment out set_signal does anything change?

**Comment by advera68** [comment]
Yes, it does, but if I'm allowed I'm going to explain what I have in the two environments that I have.

- 2 production SERVERS with Ubuntu 14.04.1 , SDK 10.3.1, bmdcapture.cpp doe not have set_signal() function.   /proc/.../status   ->  SigCgt: 0000000180000000  (i.e, no signal)

- 1 test SERVER with  Ubuntu 16.04 LT, SDK 10.6.5, bmdcapture.cpp has got set_signal() function. 
/proc/.../status   -> SigCgt: 0000000180004002  (i,e     signal(SIGINT , exit_handler);    signal(SIGTERM, exit_handler);    what is written in bmdcapture.cpp )  ,  by the way, if I comment out set_signal()  then /proc/.../status informs SigCgt: 0000000180000000  (i.e, no signal). So, it works properly.

On the other hand I observed Capture process registers 0000000180004003 , i.e SIGHUP, SIGINT, and SIGTERM.

I used to stop  bmdcapture  with  kill -9, ... I don't know it it has anything to do but I assure doing like this it turned the system in Oops state in one week or one week and a half.

As it seems to be this state doesn't occur using Capture and the treatment of the signal is different, I have decide to add   signal(SIGHUP , exit_handler); to set_signal()  in order to have the same behaviour than Capture, and stop 'bmdcapture' process using  kill -15 instead of kill -9.

We can keep in touch, if you want. 

Best Regards.

**Comment by lu-zero** [comment]
I'll have a look soon about sighup and what they did in capture soon.

**Comment by advera68** [comment]
Hi Luca, just to tell you I think the modifications done to 'bmdcapture' have fixed the problem which turned the kernel in Oops state.  As I told you in the previous post I added SIGHUP to set_signal() and I stop 'bmdcapture' which 'kill -15'.

My server has been working like this for more than one month and never entered in Oops state, capturing video continuously  and stopping as events were written in Marina AsrunLog, so, if you don't mind  I will close this issue.

Thanks a lot.

Best Regards.

**Comment by lu-zero** [comment]
I'll add the HUP handler to cleanly exit as well. Sorry for the delay.
