### ISSUE TITLE
Unable to make bmdtools on mac os 10.11.6

### ISSUE THREAD

**Issue by sfahadshahzad** [lu-zero/bmdtools#79]
Hi,

Trying to build but got error " sudo make SDK_Path=/Users/administrator/Downloads/BlackmagicSDK/Mac/include/
Password:
make: *** No rule to make target `../../include/DeckLinkAPIDispatch.cpp', needed by `bmdcapture'.  Stop."

Regards,

Fahad

**Comment by lu-zero** [comment]
Looks like you have a typo, it is `SDK_PATH`.

**Comment by sfahadshahzad** [comment]
Now the SDK path is correct but i am still unable to make.

find the errors below.

administrator$ make SDK_PATH=/Users/administrator/bmdtools/SDK/Mac/include/
g++ -o bmdcapture bmdcapture.cpp modes.cpp /Users/administrator/bmdtools/SDK/Mac/include//DeckLinkAPIDispatch.cpp  `pkg-config --cflags libavcodec libavformat libswscale libavutil` -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -Wno-multichar -I /Users/administrator/bmdtools/SDK/Mac/include/ -fno-rtti -g -framework CoreFoundation -DHAVE_CFSTRING  `pkg-config --libs libavcodec libavformat libswscale libavutil` -lm -ldl -lpthread -framework CoreFoundation
bmdcapture.cpp:95:9: warning: 'av_free_packet' is deprecated [-Wdeprecated-declarations]
        av_free_packet(&pkt->pkt);
        ^
/usr/local/include/libavcodec/avcodec.h:3914:6: note: 'av_free_packet' has been explicitly marked deprecated here
void av_free_packet(AVPacket *pkt);
     ^
bmdcapture.cpp:117:30: warning: 'av_dup_packet' is deprecated [-Wdeprecated-declarations]
    if (pkt != &flush_pkt && av_dup_packet(pkt) < 0) {
                             ^
/usr/local/include/libavcodec/avcodec.h:3905:5: note: 'av_dup_packet' has been explicitly marked deprecated here
int av_dup_packet(AVPacket *pkt);
    ^
bmdcapture.cpp:207:25: warning: 'codec' is deprecated [-Wdeprecated-declarations]
    c             = st->codec;
                        ^
/usr/local/include/libavformat/avformat.h:712:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
bmdcapture.cpp:247:25: warning: 'codec' is deprecated [-Wdeprecated-declarations]
    c             = st->codec;
                        ^
/usr/local/include/libavformat/avformat.h:712:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
bmdcapture.cpp:302:13: warning: 'codec' is deprecated [-Wdeprecated-declarations]
    c = st->codec;
            ^
/usr/local/include/libavformat/avformat.h:712:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
bmdcapture.cpp:386:19: warning: 'codec' is deprecated [-Wdeprecated-declarations]
    c = audio_st->codec;
                  ^
/usr/local/include/libavformat/avformat.h:712:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
bmdcapture.cpp:418:19: warning: 'codec' is deprecated [-Wdeprecated-declarations]
    c = video_st->codec;
                  ^
/usr/local/include/libavformat/avformat.h:712:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
7 warnings generated.
ld: can't open output file for writing: bmdcapture, errno=13 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bmdcapture] Error 1


Regards,

Fahad

**Comment by lu-zero** [comment]
```
 ld: can't open output file for writing: bmdcapture, errno=13 for architecture x86_64
```

Looks like you are out of space.

**Comment by sfahadshahzad** [comment]
i have morethen 200GB available on my mac
Fahad

**Comment by lu-zero** [comment]
make sure the directory is writable then =/ it is quite strange, here is
working fine.
