### ISSUE TITLE
bmdplay with -p 10

### ISSUE THREAD

**Issue by otcenas** [lu-zero/bmdtools#81]
Hi,

bmdplay in 10 bit mode end with segfault (8 bit mode works without any problem):

Starting program: /home/digital/Blackmagic DeckLink SDK 10.8/Linux/Samples/bmdtools/bmdplay -C 1 -m 8 -O 4 -p 10 -f /tmp/out.nut
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Input #0, nut, from '/tmp/out.nut':
  Metadata:
    major_brand     : qt
    minor_version   : 512
    compatible_brands: qt
    encoder         : Lavf56.40.101
  Duration: 00:00:09.98, start: 0.000000, bitrate: 1663526 kb/s
    Stream #0:0(eng): Video: rawvideo (Y3[10][10] / 0xA0A3359), yuv422p10le, 1920x1080, 25 tbr, 51200 tbn, 51200 tbc (default)
    Metadata:
      handler_name    : DataHandler
      encoder         : Lavc56.60.100 rawvideo
    Stream #0:1(eng): Audio: pcm_s16le (PSD[16] / 0x10445350), 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Metadata:
      handler_name    : DataHandler
      encoder         : Lavc56.60.100 pcm_s16le
[New Thread 0x7fffe8db9700 (LWP 4601)]
[New Thread 0x7fffe85b8700 (LWP 4602)]
[New Thread 0x7fffe7db7700 (LWP 4603)]
[New Thread 0x7fffe75b6700 (LWP 4604)]
[Thread 0x7fffe75b6700 (LWP 4604) exited]
Selected mode: 1080i50

[New Thread 0x7fff674f7700 (LWP 4605)]
[New Thread 0x7fff66cf6700 (LWP 4606)]
[New Thread 0x7fff664f5700 (LWP 4607)]

Thread 1 "bmdplay" received signal SIGSEGV, Segmentation fault.
0x00007ffff636e940 in ?? () from /usr/lib/x86_64-linux-gnu/libswscale-ffmpeg.so.3
(gdb)

**Comment by lu-zero** [comment]
FFmpeg is not supported.
