### ISSUE TITLE
bmdplay interlace video format problem

### ISSUE THREAD

**Issue by sbelet** [lu-zero/bmdtools#86]
Hello,

We have 1080p25 video source and we try to output 1080i50.
Just setting video mode to -m 7 (1080i50) seems to makes output in interlace.
So questions :
1. Is it enough for interlace output ? if yes, is it Top field first or bottom field first?
2. If not, what setting we should set?

Another thing if we choose (-m 4) 1080p25 mode, on AJA device the signal seems 1080psf25, some other device says it's 1080i50. Is that normal ? or by default bmdplay sets it to psf.

3. In bmdplay, is there any setting about this psf ?

(The card we use: Decklink 12G Extreme 4K)

Thank you.

**Comment by lu-zero** [comment]
You need to convert it to the correct format first.
