### ISSUE TITLE
AVCodecParameters

### ISSUE THREAD

**Issue by MTNTheCompWiz** [lu-zero/bmdtools#87]
Trying to build bmdcapture... and getting a bunch of errors all pointing to the fact that "AVCodecParameters" is nowhere in existence in the current SDK (10.9) or bmdtools repo.  I have also checked 10.8... and it is also not present.  I will try the previous version of bmdtools before the "AVCodecParameters" and report back.

> bmdcapture.cpp: In function ‘AVStream* add_audio_stream(AVFormatContext*, AVCodecID)’:
> bmdcapture.cpp:197:5: error: ‘AVCodecParameters’ was not declared in this scope
>      AVCodecParameters *par;
>      ^
> bmdcapture.cpp:197:24: error: ‘par’ was not declared in this scope
>      AVCodecParameters *par;
>                         ^
> bmdcapture.cpp:206:27: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
>      par             = st->codecpar;
>                            ^
> bmdcapture.cpp: In function ‘AVStream* add_video_stream(AVFormatContext*, AVCodecID)’:
> bmdcapture.cpp:220:5: error: ‘AVCodecParameters’ was not declared in this scope
>      AVCodecParameters *par;
>      ^
> bmdcapture.cpp:220:24: error: ‘par’ was not declared in this scope
>      AVCodecParameters *par;
>                         ^
> bmdcapture.cpp:229:27: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
>      par             = st->codecpar;
>                            ^
> bmdcapture.cpp: In function ‘AVStream* add_data_stream(AVFormatContext*, AVCodecID)’:
> bmdcapture.cpp:254:5: error: ‘AVCodecParameters’ was not declared in this scope
>      AVCodecParameters *par;
>      ^
> bmdcapture.cpp:254:24: error: ‘par’ was not declared in this scope
>      AVCodecParameters *par;
>                         ^
> bmdcapture.cpp:263:15: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
>      par = st->codecpar;
>                ^
> Makefile:58: recipe for target 'bmdcapture' failed
> make: *** [bmdcapture] Error 1
>

**Comment by lu-zero** [comment]
You should use a current [Libav](https://github.com/libav/libav). at least libav12 or master.
