### ISSUE TITLE
Multiple Concurrent Captures on Decklink Duo 2 fail on some interfaces

### ISSUE THREAD

**Issue by PreDeToR** [lu-zero/bmdtools#88]
Hi Guys

I have 2 "Decklink Duo 2"  cards, which should allow me to capture 8 SDI streams at a time, yet for some of the capture interfaces I keep getting "Failed to enable video input. Is another application using the card?"

/root/bmdtools/bmdcapture -C 5 -m 1 -A 2 -V 4 -M 4 -F nut -d 1 -v -f pipe:1   -- Works Fine
/root/bmdtools/bmdcapture -C 1 -m 1 -A 2 -V 4 -M 4 -F nut -d 1 -v -f pipe:1   -- Returns above error.                                                                                                                                                                       

Is there anything I need to do/enable to be able to capture on all 8 SDI interfaces at the same time?

**Comment by ggnull35** [comment]
You need to set right duplex mode to the card for your usage case.
bmdcapture does not set it.

**Comment by PreDeToR** [comment]
Thanks @ggnull35 . I managed to set the mode on cards and its working now.
